Biller/config/routes.rb
Rails.application.routes.draw do
  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  	resources :accounts, :employees , :proyects
  	 root 'accounts#index'
end

Biller/app/models/account.rb
class Account < ApplicationRecord
	has_many :account_entries

	validate :name_is_valid

	def name_is_valid
		if name.length < 3
			errors.add(:name, "name cannot be empty or less than two characters")
		end
	end
end 

Biller/app/models/account_entry.rb
class AccountEntry < ApplicationRecord
	belongs_to :account
end

Biller/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Biller/app/models/customer.rb
class Customer < Account
	has_many :time_entries
end

Biller/app/models/employee.rb
class Employee < Account
	has_many :time_entries
	has_and_belongs_to_many :proyects, :join_table => "employees_proyects" 
	
	def total_hours
		time_entries.sum(:time)
	end

	def log_time(amount, customer)
		TimeEntry.create(time: amount, employee: self, account: customer) 
	end
end

Biller/app/models/proyect.rb
class Proyect < ApplicationRecord
	belongs_to :customer
	has_and_belongs_to_many :employees, :join_table => "employees_proyects" 
end

Biller/app/models/time_entry.rb
class TimeEntry < AccountEntry
	belongs_to :employee, required: false
end

Biller/app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
	def index
		@accounts = Account.all
	end
	def show
		@account = Account.find(params[:id])
	end
	def destroy
		@account = Account.find(params[:id])
		if @account.destroy
			flash[:success] = "the account was deleted."
			redirect_to accounts_path
		else 
			flash[:error] = "has an error while deleting."
			render action: :new
		end
	end
	def new
		@account = Account.new
	end	
	def create 
		@account = Account.new(account_param)
		@account.type = "Customer"
		if @account.save
			flash[:success] = "the account was saved."
			redirect_to accounts_path
		else 
			flash[:error] = "has an error while saving."
			render action: :new
		end
	end

	private
	def account_param 
		params[:account].permit(:name, :type, :email, :about)
	end  
end

Biller/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Biller/app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
	def index
		@employees = Employee.all
	end
	def show
		@employee = Employee.find(params[:id])
	end
	def destroy
		@employee = Employee.find(params[:id])
		if @employee.destroy
			flash[:success] = "the account was deleted."
			redirect_to employees_path
		else 
			flash[:error] = "has an error while deleting."
			render action: :new
		end
	end
	def new
		@employee = Employee.new
	end	
	def create 
		@employee = Employee.new(employee_param)
		if @employee.save
			flash[:success] = "the employee was saved."
			redirect_to employees_path
		else 
			m=""
			@employee.errors.full_messages.each do |message|
      	 		m += message 
    		end
			flash[:error] = "has an error while saving the employee: #{m}." 
			render action: :new
		end
	end

	private
	def employee_param 
		params[:employee].permit(:name, :email)
	end  
end

Biller/app/controllers/proyects_controller.rb
class ProyectsController < ApplicationController
end

Biller/app/helpers/accounts_helper.rb
module AccountsHelper
end

Biller/app/helpers/application_helper.rb
module ApplicationHelper
end

Biller/app/helpers/employees_helper.rb
module EmployeesHelper
end

Biller/app/helpers/proyects_helper.rb
module ProyectsHelper
end

Biller/app/views/accounts/_form.html.erb


<ul>
	<li>
		<%= form.label :name %>
		<%= form.text_field :name %>		
	</li>
	<li>
		<%= form.label :email %>
		<%= form.text_field :email %>
	</li>
	<li>
		<%= form.label :about %>
		<%= form.text_field :about %>
	</li>
</ul>

<% form.label :type %>
<% form.text_field :type %>

<p><%= form.submit "Save" %> 
<%= link_to "Cancel",accounts_path %></p>

Biller/app/views/accounts/index.html.erb

<p id="notice"><%= notice %></p>
<h1>Cuscomers</h1>

<% @accounts.each do |account| %>
	<% if account.is_a?(Customer) %>
		<ul>
			<li><%= link_to account.name, account_path(account) %></li>
			<li><%= account.type.to_s %></li>
			<li><%= link_to "Delete", account_path(account), method: :delete, data: { confirm: 'Are you sure?' } %></li>			
		</ul>
	<% end %>	
<% end %>

<p><%= link_to "Create Customer", new_account_path %></p>

Biller/app/views/accounts/new.html.erb
<h1> Create Customer </h1>
<%= form_for @account do |form| %>
  	<%= render partial: form %>
<% end %> 

Biller/app/views/accounts/show.html.erb
<h1><%= @account.name %></h1>

<h3>Account Entries</h3>

<table>
	<% @account.account_entries.each do |e| %>
	<tr>
		<td><%= e.inspect %></td>
	</tr>
	<% end %>
</table>
<% if @acount.is_a?(Employee) %>
	<h3>Time Entries</h3>

	<table>
		<% @account.time_entries.each do |t| %>
		<tr>
			<td><%= t.inspect %></td>
		</tr>
		<% end %>
	</table>
<% end %>

Biller/app/views/employees/_form.html.erb
<ul>
	<li>
		<%= form.label :name %>
		<%= form.text_field :name %>		
	</li>
	<li>
		<%= form.label :email %>
		<%= form.text_field :email %>
	</li>
</ul>

<p><%= form.submit "Save" %> 
<%= link_to "Cancel",employees_path %></p>

Biller/app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Employees</h1>

<% @employees.each do |employee| %>
	<ul>
		<li><%= link_to employee.name, employee_path(employee) %></li>
		<li><%= employee.type.to_s %></li>
		<li><%= link_to "Delete", employee_path(employee), method: :delete, data: { confirm: 'Are you sure?' } %></li>			
	</ul>
<% end %>	

<p><%= link_to "Create Employee", new_employee_path %></p>

Biller/app/views/employees/new.html.erb
<h1> Create Employee </h1>
<%= form_for @employee do |form| %>
  	<%= render partial: form %>
<% end %> 

Biller/app/views/employees/show.html.erb
<h1><%= @account.name %></h1>

<% if @acount.is_a?(Employee) %>
	<h3>Time Entries</h3>

	<table>
		<% @account.time_entries.each do |t| %>
		<tr>
			<td><%= t.inspect %></td>
		</tr>
		<% end %>
	</table>
<% end %>

Biller/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Biller</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <header>
            <ul id="nav">
                <li><%= link_to "Customers", accounts_path %></li>   
                <li><%= link_to "Employees", employees_path %></li>
                <li><%= link_to "Projects", proyects_path %></li>
            </ul>
        </header>
        <div>
            <% flash.each do |type,message| %>
                <div class="alert flash <%= type %>">
                    <%= message %>
                </div>
            <% end %>
        </div>

        <br></br>
        <div class= "models">
            <%= yield %>
        </div>
    </body>
</html>